name: Build do2_refill.zip
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: do2_refill
          retention-days: 1
          path: |
            ./Decked Out 2 Refill Datapack
            !./Decked Out 2 Refill Datapack/data/do2_refill/functions/dev
            